### ISSUE TITLE
Health?

### ISSUE THREAD

**Issue by bobhenl** [kii-chan-reloaded/GeneticChickengineering#10]
Hi, what is health used for? Only when chickens are spawned?
![image](https://user-images.githubusercontent.com/18662086/108098199-61df8f80-7083-11eb-8d8d-e81c9f5db768.png)

Or shouldn't it work somehow that chicken can "dye" in machine after specific time due to health? This may be cool

Or may you could add that chickens will product only in daylight and in the night they will sleep (some energy to them).

**Comment by kii-chan-reloaded** [comment]
Health is the chicken's actual health. Chickens in Minecraft have 2 hearts (4 health), and if they get damaged then the health value in the display will change to reflect that. That all is done by code that I fully copied from Mob Capturer, and for what it's worth, it will also add a notation if the captured chicken is on fire.

I had previously thought about adding a health mechanic to GCE, however the problem is that there is no way in vanilla Minecraft to heal a chicken outside of brewing splash potions of healing. I abandoned that train of thought because I didn't feel that adding a health station really fit with the theme of the plugin. I suppose if people want more of a challenge then I could make that an optional setting that enables the machine.

As for the day/night thing, I don't think I'll persue this idea if there is an option for health reduction. That said for now, if you want that specific feature in your game, you could move your GCE setup to it's own solar panel power network. It will lose power at night and the chickens would stop producing.

**Comment by bobhenl** [comment]
about day/night, we wanted it to make it a little bit more difficult for players. But ok, if you could add health in the future it could be great. Then it could be closed now.
