### ISSUE TITLE
Only getting feather chickens

### ISSUE THREAD

**Issue by Boomer-1** [kii-chan-reloaded/GeneticChickengineering#3]
Do you have a list or table put together of the odds of each type of chicken forming from the dna sequencer? I've only gotten feather chickens after running about 30 of them thru the dna sequencer?

**Comment by kii-chan-reloaded** [comment]
All chickens caught in the overworld will be Feather chickens to begin with. You have to find chickens that have one recessive allele (Aa instead of AA), then breed it in a Private Coop with another chicken with a recessive allele of the same type to get baby chickens that can produce other resources.

For example, say you catch two chickens: one has DNA `BbCCDDFFSSWW`, the other has `BbCCDDFfSSWW`. Notice that both of them have one recessive allele in the `B` gene. If these two chickens are bred, there will be a 25% chance that the child will be `BB`, a 50% chance that it will be `Bb`, and a 25% chance that it will be `bb`. When you get lucky enough to get the `bb` child, you will then have a Bone chicken. Furthermore, because one parent is `Ff`, there will be a 50% chance that the child will be `FF` and a 50% chance it will be `Ff`. Ideally, you would want to keep breeding these two chickens until you get the 25% chance `bb` and the 50% chance `FF`, since having that extra `f` allele will cause interference in resource generation (make it produce slower).

In your `config.yml`, there are two relevant settings: `max-mutation` and `mutation-rate`. `max-mutation` takes a number from 1-6 and dictates how many recessive alleles an overworld chicken can be found with: the default is 2. `mutation-rate` is a number from 1-100 that represents the percent chance that an overworld chicken will have at least 1 recessive allele: the default is 50. If you are having issues finding chickens to breed, raising these settings can make getting started a little easier (or you can lower them to make it harder).

**Comment by Boomer-1** [comment]
that helps. Can I suggest editing the wiki description of how this works? When you've collected two or more favorable chickens, - that doesn't give enough info. Shortly I'm going to go back to the world and see if I can get this to give me a favorable chicken :^). I want to try and release a video on this today on my channel.. I'll touch base in a bit. thanks for the feedback

**Comment by kii-chan-reloaded** [comment]
A real wiki has been on my to-do list for a while, but it's been low priority since I hadn't really pushed the plugin out into the public before today. I'll probably start in on that tonight, but for now this sleepy gal is late to a date with her pillow... 😴

**Comment by Boomer-1** [comment]
kii-chan, a lot of people are really hoping you are able to come back and fix chickengineering. it's become a pretty popular addon, and with the release of SF Dev 925, there were 2 major problems that have been reported. We would greatly appreciate any insights or help you can provide in fixing them.
