### ISSUE TITLE
Error + block disappears

### ISSUE THREAD

**Issue by bobhenl** [kii-chan-reloaded/GeneticChickengineering#4]
Hi, when you try put Pocket chicken into these blocks (Genetic Sequencer, Excitation Chamber, Privte Coop, Boosted excitation chamber) then the block disappears and you'll get this error:

https://pastebin.com/tXLLHACH
(from error log from slimefun folder + second part from console)

**Comment by bobhenl** [comment]
And also when you click with Pocket Chicken on specific blocks mentioned on wiki / sf guide, like water, it spawns normal chickens:
![image](https://user-images.githubusercontent.com/18662086/106390800-80d6f400-63ea-11eb-9fd0-405be2d53fc7.png)

**Comment by kii-chan-reloaded** [comment]
Thank you for reporting this to me. I had missed one instance of getting a bit of JSON that could return null, hence the NullPointerException and the blocks disappearing. I will be releasing a patch shortly. Am I right in assuming that you cheated the pocket chicken into your inventory?

As for your other note about only spawning normal chickens... I'm not entirely sure that I understand the issue, but I will try to answer. If these were cheated from the SF guide, then currently the custom names are not set on initial spawn (coincidentally, due to that same bit of JSON being null). If they get picked up with a chicken net, then replaced, the chickens would have the correct resource names shown. I'm not sure what you're referring to by "specific blocks mentioned on wiki / sf guide" though, since you may release a pocket chicken onto any block face.

My apologies for not entirely understanding. If I am misguided, please let me know.

**Comment by bobhenl** [comment]
yes I've cheated it to my inv. And thanks, I'll specify more if there's some problem
