### ISSUE TITLE
More settings in config?

### ISSUE THREAD

**Issue by bobhenl** [kii-chan-reloaded/GeneticChickengineering#8]
Hi, could you add mre settings in config to make it less OP?

**Comment by kii-chan-reloaded** [comment]
What sort of settings do you have in mind to nerf chickens? Off the top of my head, I can think of having a customizable base time per resource or having a customizable percent chance that a chicken will make an egg instead of a resource. If you have other suggestions, I will gladly listen.

If you had customizable resources in mind, I have previously put some thought into that. I ended up finding that a **significant** chunk of the plugin would need rewritten to make that work, and *a ton* of niche cases would need to be accounted for. I'm not saying it's impossible, but it's almost certainly not going to be the fix that closes this issue. It'll probably be on the roadmap for v2.0 though if I can figure out the logistics of it all.

**Comment by bobhenl** [comment]
Yeah I have meant time per resource or also percent chance.

**Comment by kii-chan-reloaded** [comment]
Both of these features are now available in the latest builds! The `jar` in the v1.1.0 release here on GitHub has already been updated, or build 9 on the [Slimefun build server](https://thebusybiscuit.github.io/builds/kii-chan-reloaded/GeneticChickengineering/master/) will have the patches when the site refreshes.

Thanks for the suggestion!

**Comment by bobhenl** [comment]
And may you could add in next update to also do these options in specific items in slimefun file.

And btw, could we also disable for ex. netherite chickens somehow?
